name: Test all the things

on: [push, pull_request]


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git fetch --depth=1 origin '+refs/tags/*:refs/tags/*'
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8.0-292
      - name: Test
        run: sbt ";+instrumentation/publishLocal;+test"
